version: '3'
services:
  app:
    env_file:
      - app.env
    build: ./app
    restart: always
    container_name: app
    volumes:
      - ./app/sistema_evaluacion_codigo:/code
    depends_on:
      - bd
  bd:
    image: mariadb
    restart: always
    env_file:
      - bd.env
    volumes:
      - ./data:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./app/sistema_evaluacion_codigo/static_production:/static
      - ./app/sistema_evaluacion_codigo/media:/media
    depends_on:  
      - app
